name: Venture Out
favicon: null
layout_spectrum: 0.8924731
typography_spectrum: 0.2903226
title: Venture Out
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00315c'
    - '#7fa6b5'
    - '#cecdae'
    - '#6e3f01'
    - '#d47801'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.9102597
purpose: []
